# Generated by Django 5.0.6 on 2024-06-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(help_text='Введите дату события', null=True, verbose_name='Дата события'),
        ),
    ]
