# Generated by Django 5.0.6 on 2024-06-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contact_remove_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sport',
            field=models.TextField(),
        ),
    ]
