# Generated by Django 5.0.6 on 2024-06-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_contact_first_name_alter_contact_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
